on:
  push:
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Check
        uses: actions/checkout@v4

      - name: Scan Terraform with Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./modulo7-iac_tooling
          soft_fail: true
          #soft_fail: false

      - name: Scan Geral do Reposit√≥rio (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './modulo7-iac_tooling'
          scanners: 'vuln,misconfig,secret'
          #exit-code: '1'
          severity: 'HIGH,CRITICAL'
          format: 'table'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Install Make
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      - name: Destroy ec2 already running the project
        id: destroy
        run: make aws-destroy
        working-directory: ./modulo7-iac_tooling

#      - name: Deploys on AWS
#        id: apply
#        run: make aws-deploy
#        working-directory: ./modulo7-iac_tooling