on:
  push:
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Check
        uses: actions/checkout@v4

      - name: Debug - Listar arquivos
        run: ls -R

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./modulo7-iac_tooling
    
      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./modulo7-iac_tooling

      - name: Terraform format
        id: fmt
        run: terraform fmt
        working-directory: ./modulo7-iac_tooling

      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ./modulo7-iac_tooling

      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve
        working-directory: ./modulo7-iac_tooling

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: ./modulo7-iac_tooling
        