on:
  push:
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        id: init
        run: terraform -chdir=./modulo7-iac_tooling init

    
      - name: Terraform Validate
        id: validate
        run: terraform -chdir=./modulo7-iac_tooling validate

      - name: Terraform format
        id: fmt
        run: terraform -chdir=./modulo7-iac_tooling fmt

      - name: Terraform Plan
        id: plan
        run: terraform -chdir=./modulo7-iac_tooling plan

      - name: Terraform destroy
        id: destroy
        run: terraform -chdir=./modulo7-iac_tooling destroy -auto-approve

      - name: Terraform Apply
        id: apply
        run: terraform apply -chdir=./modulo7-iac_tooling -auto-approve