on:
  push:
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Check
        uses: actions/checkout@v4

      - name: Debug - Listar arquivos
        run: ls -R

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Instalar Make
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      - name: Terraform destroy
        id: destroy
        run: make aws-destroy
        working-directory: ./modulo7-iac_tooling

      - name: Terraform Apply
        id: apply
        run: make aws-deploy
        working-directory: ./modulo7-iac_tooling
        